version: '3.8'  # 사용할 Docker Compose 버전

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # 데이터 지속성을 위한 볼륨 사용
    networks:
      - app-network
    restart: always  # 자동 재시작 설정

  cointrading:
    image: ${DOCKER_USERNAME}/cointrading:latest  # 애플리케이션 이미지
    container_name: cointrading
    ports:
      - "8080:8080"  # 애플리케이션 포트 연결
    environment:
      - SPRING_REDIS_HOST=redis
      - REDIS_HOST=redis
    depends_on:
      - redis  # 서비스 이름은 'redis', 'redis-container'가 아님
    networks:
      - app-network
    restart: always  # 자동 재시작 설정

volumes:
  redis-data:  # Redis 데이터를 저장할 볼륨

networks:
  app-network:
    driver: bridge
