version: '3.8'  # 사용할 Docker Compose 버전

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # 데이터 지속성을 위한 볼륨 사용
    networks:
      - app-network
    restart: always  # 자동 재시작 설정

  cointrading:
    image: ${secrets.DOCKER_USERNAME}/cointrading:latest  # 애플리케이션 이미지
    container_name: cointrading
    ports:
      - "8080:8080"  # 애플리케이션 포트 연결
    environment:
      - AES_SECRET_KEY=${{ secrets.AES_SECRET_KEY }}  # 환경 변수 설정
      - REDIS_HOST=redis
    depends_on:
      - redis  # cointrading 컨테이너가 redis 컨테이너가 실행된 후에 시작되도록 설정
    networks:
      - app-network
    restart: always  # 자동 재시작 설정

volumes:
  redis-data:  # Redis 데이터를 저장할 볼륨
networks:
  app-network:
    driver: bridge
